name: RC Internal DataMiner CICD NuGet Solution

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.[0-9]+-**"
      - "[0-9]+.[0-9]+.[0-9]+-**"

  workflow_dispatch:

jobs:

  CICD:
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/Internal NuGet Solution Master Workflow.yml@RC
    with:
      referenceName: ${{ github.ref_name }}
      runNumber: ${{ github.run_number }}
      referenceType: ${{ github.ref_type }}
      repository: ${{ github.repository }}
      owner: ${{ github.repository_owner }}
      sonarCloudProjectName: SkylineCommunications_BOOST-DailyRegression-InternalNuGet
    secrets:
      sonarCloudToken: ${{ secrets.SONAR_TOKEN }}
      nugetApiKey: ${{ secrets.NUGETAPIKEY_GITHUB }}
